# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fb_lrind_fastcpp <- function(n, alpha = 0.05, prune_threshold = 1e-15) {
    .Call(`_ExactVaRTest_fb_lrind_fastcpp`, n, alpha, prune_threshold)
}

fb_lrcc_fastcpp <- function(n, alpha = 0.05, prune_threshold = 1e-15) {
    .Call(`_ExactVaRTest_fb_lrcc_fastcpp`, n, alpha, prune_threshold)
}

